---
title: "Shiny Application Knowledge Map"
author: "Hadrien@rstudio.com"
date: "4/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(networkD3)
library(writexl)
```

## R Markdown


```{r force-network}

# create data

# nodes
nodes <- tribble(~name, ~group, ~size, ~webinar, ~time,
                 
                 # How to build a shiny app from scratch
                 "Shiny","group_1",40,"01",1,  # node 0
                 "Anatomy","group_2",1,"01",1,  # node 1
                 "UI","group_3",1,"01",5,  # node 2
                 "Layout Options","group_3",1,"01",10, # 3
                 "Sidebar","group_3",1,"01",10, # 4
                 "Grid","group_3",1, "01",10, # 5
                 "Control Widgets", "group_3",1,"01", 15, #6
                 "selectInput","group_3",1,"01",15, #7
                 "Server","group_4",1,"01",20, #8
                 "Inputs", "group_3",1,"01",20, #9
                 "Outputs","group_4",1,"01",20,   #10
                 "Reactivy","group_5",1,"01",30,  #11
                 "Tools","group_6",2,"01",45,  #12
                 "Showcase","group_6",1,"01",50, #13
                 "reactlog","group_6",1,"01",55, #14
                
                # https://shiny.rstudio.com/articles/
                "Dashboards","group_3",1,"02",60, #15
                "Tabsets","group_3",1,"02",60, #16
                "Navlists","group_3",1,"02",60, #17
                "Secondary Nav","group_3",1,"02",60, #18
                "shinyloadtest","group_6",1,"02",60, #19
                "custom UI", "group_3",1,"02",60, #20
                "Progress Indicators","group_3",1,"02",60, #21
                "GA", "group_6",1,"02",60, #22
                "profvis","group_6",1,"02",60, #23
                "plot caching","group_7",1,"02",60, #24
                "async","group_7",1,"02",60, #25
                "tuning","group_7",1,"02",60, #26
                
                # reactive programming 
                "isolate","group_5",1,"03",60, #27
                "execution scheduling","group_5",1,"03",60, #28
                "Values","group_5",1,"03",60, #29
                "Observers","group_5",1,"03",60, #30
                "Expressions","group_5",1,"03",60, #31
                

)

nodes <- as.data.frame(nodes)

# links
links <- tribble(~source, ~target, ~value, ~webinar, ~time,
                0,1,1,"01",1,  # shiny > anatomy
                1,2,1,"01",5, # anatomy > UI
                1,8,1,"01",20, # anatomy > server
                2,3,1,"01",10, # UI > layout options
                3,4,1,"01",10, # layout options > sidebar
                3,5,1,"01",10, # layout options > grid
                2,6,1,"01",15, # UI > control widgets
                6,7,1,"01",15, # control widget > selectInput
                1,8,1,"01",20, # anatomy > Server
                7,9,1,"01",20, # Server > Inputs
                7,10,1,"01",20, # Sever > Outputs
                0,11,1,"01",30, # Shiny > reactivity
                0,12,1,"01",45, # Shiny > Tools
                12,13,1,"01",50, # Tools > showcase
                12,14,1,"01",55  # Tools > reactlog
                # 6,18,1,"02",60,
                # 0,19,1,"01",30 # Shiny > Tools
                # 19,20,1,"01",30, # Tools > showcase
                # 19,21,1,"01",30,  # Tools > reactlog
                # 19,22,1,"02",60, # Tools > shinyloadtest
                # 2,23,1,"02",60, # UI > custom UI
                # 19,25,1,"02",60,
                # 19,26,1,"02",60,
                # 19,27,1,"02",60,
                # 19,28,1,"02",60,
                # 19,29,1,"02",60,
                # 2,24,1,"02", 60, # UI > Progress Indicators
                # 11,30,1,"03",60, # reactivity > isolate
                # 11,31,1,"03",60 #reactivity > execution scheduling
                
                )

links <- as.data.frame(links)

# save the workspace to the file .RData in the cwd 
save.image()

# write to flat file
write_xlsx(nodes,  "../knowledge-map-app/nodes.xlsx")
write_xlsx(links,  "../knowledge-map-app/links.xlsx")

# QA
nodes_filtered <- nodes
links_filtered <- links

# nodes_filtered <- nodes %>% filter(webinar %in% c("01"), time <= 60)
# links_filtered <- links %>% filter(webinar %in% c("01"), time <= 60)

forceNetwork(Links = links_filtered, Nodes = nodes_filtered,
             Source = "source", Target = "target",
             Value = "value", # strength of relationship (link width)
             NodeID = "name",
             Group = "group", Nodesize = "size",
             opacityNoHover = TRUE, # display labels
             opacity = 0.9,
             fontSize = 10,
             zoom = TRUE #enable zooming
            )




```

```{r forceNetwork-example}
# Load data
data(MisLinks)
data(MisNodes)
# Create graph
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.4, zoom = TRUE)


# Create graph with legend and varying node radius
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Nodesize = "size",
radiusCalculation = "Math.sqrt(d.nodesize)+6",
Group = "group", opacity = 0.4, legend = TRUE)


# Create graph directed arrows
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.4, arrows = TRUE)
## Not run:


#### JSON Data Example
# Load data JSON formated data into two R data frames
# Create URL. paste0 used purely to keep within line width.
URL <- paste0("https://cdn.rawgit.com/christophergandrud/networkD3/",
"master/JSONdata/miserables.json")
MisJson <- jsonlite::fromJSON(URL)
# Create graph
forceNetwork(Links = MisJson$links, Nodes = MisJson$nodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.4)


# Create graph with zooming
forceNetwork(Links = MisJson$links, Nodes = MisJson$nodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.4, zoom = TRUE)

# Create a bounded graph
forceNetwork(Links = MisJson$links, Nodes = MisJson$nodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.4, bounded = TRUE)


# Create graph with node text faintly visible when no hovering
forceNetwork(Links = MisJson$links, Nodes = MisJson$nodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.4, bounded = TRUE,
opacityNoHover = TRUE)



## Specify colours for specific edges
# Find links to Valjean (11)
which(MisNodes == "Valjean", arr = TRUE)[1] - 1
ValjeanInds = which(MisLinks == 11, arr = TRUE)[, 1]
# Create a colour vector
ValjeanCols = ifelse(1:nrow(MisLinks) %in% ValjeanInds, "#bf3eff", "#666")
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.8, linkColour = ValjeanCols)
## Create graph with alert pop-up when a node is clicked. You're
# unlikely to want to do exactly this, but you might use
# Shiny.onInputChange() to allocate d.XXX to an element of input
# for use in a Shiny app.
MyClickScript <- 'alert("You clicked " + d.name + " which is in row " +
(d.index + 1) + " of your original R data frame");'
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 1, zoom = FALSE,
bounded = TRUE, clickAction = MyClickScript)

```


